In [1]:
# show images inline
%matplotlib inline

# automatically reload modules when they have changed
%load_ext autoreload
%autoreload 2

import sys, os
sys.path.insert(0, os.path.abspath('..'))
import yolk
from PIL import Image

# import miscellaneous modules
import matplotlib.pyplot as plt
import cv2
import numpy as np 

Using retinanet backend


In [ ]:
import 

In [4]:
def main():
    image = np.asarray(Image.open('000000008021.jpg').convert('RGB'))
    image = image[:, :, ::-1].copy()
    image, scale = yolk.detector.preprocessing_image(image)

    model_path = os.path.join('..', 'snapshots', 'resnet50_coco_best_v2.1.0.h5')
    print(model_path)
    model = yolk.detector.load_model(model_path)

    boxes, scores, labels = model.predict_on_batch(np.expand_dims(image, axis=0))

    print(boxes)

If you see error 'compute_overlap.pyx', you have to install package!

~~~python
python setup.py build_ext --inplace
~~~

In [5]:
if __name__ == '__main__':
    main()

..\snapshots\resnet50_coco_best_v2.1.0.h5
Instructions for updating:
Colocations handled automatically by placer.
tracking <tf.Variable 'Variable:0' shape=(9, 4) dtype=float32> anchors
tracking <tf.Variable 'Variable_1:0' shape=(9, 4) dtype=float32> anchors
tracking <tf.Variable 'Variable_2:0' shape=(9, 4) dtype=float32> anchors
tracking <tf.Variable 'Variable_3:0' shape=(9, 4) dtype=float32> anchors
tracking <tf.Variable 'Variable_4:0' shape=(9, 4) dtype=float32> anchors


C:\Users\dlawo\Anaconda3\lib\site-packages\keras\engine\saving.py:341: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '


type: <class 'keras.engine.training.Model'>
[[[ 4.0901965e+02  1.6714182e+02  7.2808167e+02  6.0342035e+02]
  [ 5.0682068e-02  4.2660532e+02  5.1254114e+02  7.8583240e+02]
  [ 7.2349469e+02  4.7574936e+02  1.0670000e+03  7.9143103e+02]
  ...
  [-1.0000000e+00 -1.0000000e+00 -1.0000000e+00 -1.0000000e+00]
  [-1.0000000e+00 -1.0000000e+00 -1.0000000e+00 -1.0000000e+00]
  [-1.0000000e+00 -1.0000000e+00 -1.0000000e+00 -1.0000000e+00]]]
